import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  guidesSidebar: [
    'index',
    {
      type: "autogenerated",
      dirName: "."
    }
  ]
};

export default sidebars;
